/**
 * Types d'événements spécifiques au module Assessments
 */

export const AssessmentsEvents = {
  EXAM_CREATED: "EXAM_CREATED",
  EXAM_SUBMITTED_FOR_VALIDATION: "EXAM_SUBMITTED_FOR_VALIDATION",
  EXAM_VALIDATED: "EXAM_VALIDATED",
  EXAM_PUBLISHED: "EXAM_PUBLISHED",
  EXAM_ARCHIVED: "EXAM_ARCHIVED",
  EXAM_STATUS_CHANGED: "EXAM_STATUS_CHANGED",
  LATE_CODE_GENERATED: "LATE_CODE_GENERATED",
  LATE_CODE_USED: "LATE_CODE_USED",
} as const;
